FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV=production
ENV MONGO_URI=mongodb://127.0.0.1:27017
ENV DB_NAME=remix
ENV MONGO_URI_APP=mongodb://127.0.0.1:27017
ENV APP_DB_NAME=db
ENV BCRYPT_SALT_ROUND=10
ENV BCRYPT_PLAIN_TEXT=btaskee
ENV MAIL_SERVER_PASSWORD=gjooioyeygvapmoe
ENV MAIL_SERVER_ADDRESS=minhthiisme218@gmail.com
ENV ORIGINAL_DOMAIN=http://localhost:3000
ENV MAX_AGE_SESSION=31536000
ENV SESSION_SECRET=s3cr3t
ENV STORAGE_ACCESS_KEY=AKIAIDHBPOWNACNC4YGA
ENV STORAGE_SECRET=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
ENV STORAGE_REGION=ap-southeast-1
ENV STORAGE_BUCKET=toanphambucket
ENV GO_REST_API_URI=http://localhost:8080/api
ENV ACCESS_KEY=dumpkey

EXPOSE 3000

CMD ["npm", "run", "deploy"]
