/**
 * 27017
 */
export const ID_COLLECTIONS_NAME = [
  // STYLE 1
  'id_incentive',
  'id_weeklyPayout',
  'id_chatMessage',
  'id_userLocationHistory',
  'id_gift',
  'id_userActionHistory',
  'id_marketingCampaign',
  'id_notification',
  'id_paymentCard',
  'id_paymentTransaction',
  'id_pointTransaction',
  'id_promotionCode',
  'id_promotionHistory',
  'id_rating',
  'id_task',
  'id_taskerTaskHistory',
  'id_purchaseOrder',
  'id_transaction',
  'id_serviceChannel',
  'id_taskSchedule',
  'id_taskReportTasker',
  'id_subscription',
  'id_taskerTraining',
  'id_feedback',
  'id_outstandingPayment',
  'id_askerRating',
  'id_askerBlacklistHistory',
  'id_notComeLockHistory',
  'id_compensation',
  'id_appUserHistory',
  'id_productGroceryAssistant',
  'id_storeGroceryAssistant',
  'id_supportNotification',
  'id_penalty',
  'id_userActivation',

  // STYLE 2
  'id_FATransaction',
  'id_service',
  'id_reward',
  'id_settingSystem',
  'id_subscriptionSettings',
  'id_taskerSettings',
  'id_taskerViolate',
  'id_taskerNotViolate',
  'id_refundRequest',
  'id_refundTransaction',
  'id_userComplaint',
  'id_taskerProfile',
  'id_trainingTasker',
  'id_trainingTaskerHistory',
  'id_quizzesTrainingTasker',
  'id_historyIncomeReport2016',
  'id_historyIncomeReport2017',
  'id_historyIncomeReport2018',
  'id_historyIncomeReport2019',
  'id_historyIncomeReport2020',
  'id_historyIncomeReport2021',
  'id_historyIncomeReport2022',
  'id_historyIncomeReport2023',
  'id_bEmployee',

  // STYLE 3
  'id_comboVoucher',
  'id_journeySetting',
  'id_journeyHistory',
  'id_taskerGift',
  'id_taskerIncentive',
  'id_vatRequest',
  'id_askerFlashSaleIncentive',
  'id_taskerFlashSaleIncentive',
  'id_trainingJourneyHistory',
  'id_quizzesTrainingJourney',
  'id_trainingJourney',
  'id_askerReferralSetting',
  'id_askerReferralCampaign',
  'id_taskerPointTransaction',
  'id_taskerMarketingCampaign',
  'id_taskerWorkingHistory',
  'id_taskerWeeklyPayout',
  'id_paymentToolKitTransaction',
  'id_taskerBNPLProcess',
  'id_taskerBNPLTransaction',
  'id_userGameCampaign',
  'id_gameCampaign',
  'id_bEmployeeSetting',
  'id_payoutHistory',
  'id_thingsToKnow',
  'id_surveySetting',
  'id_surveyReport',
  'id_promotionSource',
  'id_vatInvoiceOrder',

  // Special
  'id_paymentMidtransTransaction',
  'id_paymentXenditTransaction',
];
export const TH_COLLECTIONS_NAME = [
  // STYLE 2
  'th_FATransaction',
  'th_service',
  'th_reward',
  'th_settingSystem',
  'th_subscriptionSettings',
  'th_taskerSettings',
  'th_taskerViolate',
  'th_taskerNotViolate',
  'th_refundRequest',
  'th_refundTransaction',
  'th_userComplaint',
  'th_taskerProfile',
  'th_trainingTaskerHistory',
  'th_trainingTasker',
  'th_quizzesTrainingTasker',
  'th_historyIncomeReport2016',
  'th_historyIncomeReport2017',
  'th_historyIncomeReport2018',
  'th_historyIncomeReport2019',
  'th_historyIncomeReport2020',
  'th_historyIncomeReport2021',
  'th_historyIncomeReport2022',
  'th_historyIncomeReport2023',
  'th_bEmployee',

  // STYLE 3
  'th_comboVoucher',
  'th_journeySetting',
  'th_journeyHistory',
  'th_taskerGift',
  'th_taskerIncentive',
  'th_vatRequest',
  'th_askerFlashSaleIncentive',
  'th_taskerFlashSaleIncentive',
  'th_trainingJourneyHistory',
  'th_quizzesTrainingJourney',
  'th_trainingJourney',
  'th_askerReferralSetting',
  'th_askerReferralCampaign',
  'th_taskerPointTransaction',
  'th_taskerMarketingCampaign',
  'th_taskerWorkingHistory',
  'th_taskerWeeklyPayout',
  'th_paymentToolKitTransaction',
  'th_taskerBNPLProcess',
  'th_taskerBNPLTransaction',
  'th_userGameCampaign',
  'th_gameCampaign',
  'th_bEmployeeSetting',
  'th_payoutHistory',
  'th_thingsToKnow',
  'th_surveySetting',
  'th_surveyReport',
  'th_promotionSource',
  'th_vatInvoiceOrder',

  // Special
  'shopeePayTransaction',
  'payment2C2PTransaction',
];
export const COMMON_COLLECTIONS_NAME = [
  'workingPlaces',
  'financialAccount',
  'settingCountry',
  'bannedReferralCode',
  'users_deleted',
  'askerSurvey',
];
export const VN_COLLECTIONS_NAME = [
  // STYLE 1: common for VN & TH
  // because logic legacy code, we must to put them in VN collections name storage
  'incentive',
  'weeklyPayout',
  'chatMessage',
  'userLocationHistory',
  'gift',
  'userActionHistory',
  'marketingCampaign',
  'notification',
  'paymentCard',
  'paymentTransaction',
  'pointTransaction',
  'promotionCode',
  'promotionHistory',
  'task',
  'rating',
  'taskerTaskHistory',
  'purchaseOrder',
  'transaction',
  'serviceChannel',
  'taskSchedule',
  'taskReportTasker',
  'subscription',
  'taskerTraining',
  'feedback',
  'outstandingPayment',
  'askerRating',
  'askerBlacklistHistory',
  'notComeLockHistory',
  'compensation',
  'appUserHistory',
  'storeGroceryAssistant',
  'productGroceryAssistant',
  'supportNotification',
  'penalty',
  'userActivation',

  // STYLE 2
  'FATransaction',
  'service',
  'reward',
  'settingSystem',
  'subscriptionSettings',
  'taskerSettings',
  'taskerViolate',
  'taskerNotViolate',
  'refundRequest',
  'refundTransaction',
  'userComplaint',
  'taskerProfile',
  'trainingTasker',
  'trainingTaskerHistory',
  'quizzesTrainingTasker',
  'historyIncomeReport2016',
  'historyIncomeReport2017',
  'historyIncomeReport2018',
  'historyIncomeReport2019',
  'historyIncomeReport2020',
  'historyIncomeReport2021',
  'historyIncomeReport2022',
  'historyIncomeReport2023',
  'bEmployee',

  // STYLE 3
  'vn_comboVoucher',
  'vn_journeySetting',
  'vn_journeyHistory',
  'vn_taskerGift',
  'vn_taskerIncentive',
  'vn_vatRequest',
  'vn_askerFlashSaleIncentive',
  'vn_taskerFlashSaleIncentive',
  'vn_askerReferralCampaign',
  'vn_trainingJourneyHistory',
  'vn_quizzesTrainingJourney',
  'vn_trainingJourney',
  'vn_askerReferralSetting',
  'vn_taskerPointTransaction',
  'vn_taskerMarketingCampaign',
  'vn_taskerWorkingHistory',
  'vn_taskerWeeklyPayout',
  'vn_paymentToolKitTransaction',
  'vn_taskerBNPLProcess',
  'vn_taskerBNPLTransaction',
  'vn_userGameCampaign',
  'vn_gameCampaign',
  'vn_bEmployeeSetting',
  'vn_payoutHistory',
  'vn_thingsToKnow',
  'vn_surveySetting',
  'vn_surveyReport',
  'vn_promotionSource',
  'vn_vatInvoiceOrder',

  // Special
  'vnPayTransaction',
  'zaloPayTransaction',
  'momoTransaction',
  'tikiMiniAppTransaction',
  'vn_shopeePayTransaction',
  'vn_paymentMBTransaction',
];

/**
 * 3001
 */
export const AUTH_COLLECTIONS = [
  'taskerRegister',
  'userLoginHistory',
  'actionPermissions',
  'groups',
  'userHistory',
  'requestUser',
  'notificationTemplate',
  'userDelete',
];

/**
 * @description
 * Storage collections name by iso code.
 */
export const STORAGE_COLLECTIONS_NAME = {
  VN: VN_COLLECTIONS_NAME,
  TH: TH_COLLECTIONS_NAME,
  ID: ID_COLLECTIONS_NAME,
};
